### ISSUE TITLE
hypercore would be good to add

### ISSUE THREAD

**Issue by resession** [worldpeaceenginelabs/TRUE-P2P-CONCEPT#1]
would it be possible to add support for hypercore

https://hypercore-protocol.org/
https://github.com/hypercore-protocol

**Comment by worldpeaceenginelabs** [comment]
it looks like it. I will add it to the suggested repos for this project.

Thank you very much.

btw: would you be able to add the hypercore functionality into the true-p2p repo as a module?
I am pretty new to coding, so i need coders who are more experienced then me.
